### ISSUE TITLE
Exclusion tags should be supported

### ISSUE THREAD

**Issue by ebernhardson** [jdlrobson/Barry-the-Browser-Test-Bot#3]
Currently we can only specify a set of tags to include, i think should also be able to  list the tags to exclude.  Excludes passed to cucumber are done as '~@expected_failures'.  The easiest way to implement this would be to not handle the @ in the code, but just expect the command line to include the appropriate @ or ~@ symbol.

**Comment by jdlrobson** [comment]
Sounds good!
